"""Automated recommendation delivery.

Turns a recommendation-engine analysis into human-readable reports and pushes
them through the configured channels:

* Always     - console summary + markdown/JSON report files under ``outputs/``
* Optional   - SMTP email report (configure ``DELIVERY['email']``)
* Optional   - Telegram bot message (configure ``DELIVERY['telegram']``)

The "file" and "console" channels work out of the box, so delivery is fully
functional even without external credentials.
"""

import os
import sys
import json
import smtplib
import datetime as dt
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

import urllib.request
import urllib.parse

from config import REPORT_DIR, DELIVERY

# Windows consoles default to cp1252 which cannot encode emoji used in reports.
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')


PRIORITY_ICON = {'High': '🔴', 'Medium': '🟠', 'Low': '🟡'}


def _fmt_float(value, digits=1):
    if value is None:
        return 'N/A'
    try:
        return f'{float(value):.{digits}f}'
    except (TypeError, ValueError):
        return str(value)


def format_markdown(analysis):
    """Render the analysis dict as a readable markdown report."""
    ts = analysis.get('timestamp', dt.datetime.now().isoformat(timespec='seconds'))
    lines = []
    lines.append(f'# 🌾 Farm Advisory Report — {analysis.get("crop", "Crop")}')
    lines.append('')
    lines.append(f'> Generated: {ts}  ·  Node: `{analysis.get("node_id", "-")}`')
    lines.append('')
    lines.append(f'**Summary:** {analysis["summary"]}')
    lines.append('')

    section_no = 0

    def section(title):
        nonlocal section_no
        section_no += 1
        return f'## {section_no}. {title}'

    sensor = analysis.get('sensor', {})
    lines.append('---')
    lines.append(section('Live Sensor Telemetry'))
    lines.append('')
    lines.append('| Feature | Reading |')
    lines.append('| --- | --- |')
    for feature in ('Temperature', 'Humidity', 'Moisture', 'Nitrogen',
                    'Phosphorus', 'Potassium', 'PH', 'Light_Intensity'):
        if feature in sensor:
            lines.append(f'| {feature} | {_fmt_float(sensor[feature])} |')
    if sensor.get('yield_forecast') is not None:
        lines.append(f'| **Yield forecast** | **{_fmt_float(sensor["yield_forecast"], 2)}** |')
    lines.append('')

    lines.append('### Disease diagnosis (Random Forest)')
    lines.append('')
    lines.append(f'- Predicted state: **{sensor.get("disease_prediction", "N/A")}**')
    risk = sensor.get('top_disease_risk')
    if risk and risk.get('disease'):
        lines.append(f'- Top disease risk: **{risk["disease"]}** '
                     f'({risk.get("probability", 0) * 100:.1f}%)')
    lines.append('')

    weather = analysis.get('weather')
    lines.append('---')
    lines.append(section('Live Weather'))
    if weather:
        lines.append('')
        lines.append(f'- Condition: **{weather.get("weather_label")}** '
                     f'({weather.get("source")})')
        lines.append(f'- Temperature: {_fmt_float(weather.get("temperature"))} °C  ·  '
                     f'Humidity: {_fmt_float(weather.get("humidity"))}%  ·  '
                     f'Precipitation: {_fmt_float(weather.get("precipitation_mm"))} mm  ·  '
                     f'Wind: {_fmt_float(weather.get("wind_speed_kmh"))} km/h')
    else:
        lines.append('*(weather feed unavailable)*')
    lines.append('')

    leaf = analysis.get('leaf')
    sky = analysis.get('sky')
    if leaf or sky:
        lines.append('---')
        lines.append(section('Vision Models'))
        lines.append('')
        if leaf:
            lines.append(f'- **Leaf image:** *{leaf["prediction"]}* '
                         f'({leaf.get("probability", 0) * 100:.1f}%)')
        if sky:
            lines.append(f'- **Sky image:** *{sky["prediction"]}* '
                         f'({sky.get("probability", 0) * 100:.1f}%)')
        lines.append('')

    lines.append('---')
    lines.append(section('Recommended Actions'))
    lines.append('')
    recs = analysis.get('recommendations', [])
    if not recs:
        lines.append('✅ No urgent actions required — keep the current management plan.')
    else:
        lines.append('| Priority | Category | Action | Rationale |')
        lines.append('| --- | --- | --- | --- |')
        for rec in recs:
            icon = PRIORITY_ICON.get(rec['priority'], '⚪')
            lines.append(f'| {icon} {rec["priority"]} | {rec["category"]} | '
                         f'{rec["action"]} | {rec["rationale"]} |')
    lines.append('')
    lines.append('---')
    lines.append('*Automatically generated by the Farm Advisory Platform.*')
    return '\n'.join(lines)


class ReportDelivery:
    """Writes report files and pushes them through configured channels."""

    def __init__(self, report_dir=REPORT_DIR, config=None):
        self.report_dir = report_dir
        self.config = config or DELIVERY
        os.makedirs(report_dir, exist_ok=True)

    def _timestamp(self, analysis):
        return analysis.get('timestamp', dt.datetime.now().isoformat(timespec='seconds'))

    def _file_basename(self, analysis):
        stamp = self._timestamp(analysis).replace(':', '').replace(' ', '_')
        node = analysis.get('node_id', 'farm')
        return f'advisory_{node}_{stamp}'

    # ------------------------------------------------------------- channels
    def deliver_file(self, analysis):
        basename = self._file_basename(analysis)
        md_path = os.path.join(self.report_dir, f'{basename}.md')
        json_path = os.path.join(self.report_dir, f'{basename}.json')

        with open(md_path, 'w', encoding='utf-8') as handle:
            handle.write(format_markdown(analysis))
        with open(json_path, 'w', encoding='utf-8') as handle:
            json.dump(analysis, handle, indent=2, default=str)

        return {'markdown': md_path, 'json': json_path}

    def deliver_console(self, analysis):
        print('\n' + '=' * 72)
        print(format_markdown(analysis))
        print('=' * 72)

    def deliver_email(self, analysis):
        cfg = self.config.get('email', {})
        if not cfg.get('enabled') or not cfg.get('to'):
            return None
        subject = f"[Farm Advisory] {analysis['summary'][:60]}"
        message = MIMEMultipart('alternative')
        message['Subject'] = subject
        message['From'] = cfg['username']
        message['To'] = ', '.join(cfg['to'])
        message.attach(MIMEText(format_markdown(analysis), 'markdown'))
        try:
            with smtplib.SMTP(cfg['smtp_host'], cfg['smtp_port'], timeout=20) as server:
                server.starttls()
                server.login(cfg['username'], cfg['password'])
                server.sendmail(cfg['username'], cfg['to'], message.as_string())
            return {'sent': True, 'to': cfg['to']}
        except Exception as exc:
            print(f'[delivery] email failed: {exc}')
            return {'sent': False, 'error': str(exc)}

    def deliver_telegram(self, analysis):
        cfg = self.config.get('telegram', {})
        if not cfg.get('enabled') or not cfg.get('bot_token') or not cfg.get('chat_id'):
            return None
        text_lines = [f"🌾 Farm Advisory ({analysis['node_id']}):\n{analysis['summary']}"]
        for rec in analysis.get('recommendations', [])[:5]:
            icon = PRIORITY_ICON.get(rec['priority'], '•')
            text_lines.append(f"{icon} [{rec['priority']}] {rec['action']}")
        text = '\n'.join(text_lines)
        url = f"https://api.telegram.org/bot{cfg['bot_token']}/sendMessage"
        payload = urllib.parse.urlencode({'chat_id': cfg['chat_id'], 'text': text}).encode()
        try:
            with urllib.request.urlopen(url, data=payload, timeout=20):
                return {'sent': True}
        except Exception as exc:
            print(f'[delivery] telegram failed: {exc}')
            return {'sent': False, 'error': str(exc)}

    # ---------------------------------------------------------------- main
    def deliver(self, analysis):
        """Push the analysis through all enabled channels; returns a log."""
        log = {'channels': {}}
        if self.config.get('console'):
            self.deliver_console(analysis)
            log['channels']['console'] = True
        if self.config.get('file'):
            paths = self.deliver_file(analysis)
            log['channels']['file'] = paths
            print(f"[delivery] report written -> {paths['markdown']}")
        email = self.deliver_email(analysis)
        telegram = self.deliver_telegram(analysis)
        if email:
            log['channels']['email'] = email
        if telegram:
            log['channels']['telegram'] = telegram
        return log


if __name__ == '__main__':
    # Standalone self-check on a dummy analysis.
    sample = {
        'crop': 'Wheat', 'node_id': 'DEMO', 'timestamp': dt.datetime.now().isoformat(timespec='seconds'),
        'summary': 'Demo report only',
        'sensor': {'Temperature': 26.0, 'Humidity': 60.0, 'Moisture': 48.0,
                   'Nitrogen': 48.0, 'Phosphorus': 42.0, 'Potassium': 40.0,
                   'PH': 6.6, 'Light_Intensity': 620.0, 'disease_prediction': 'Healthy',
                   'yield_forecast': 70.0},
        'weather': None, 'leaf': None, 'sky': None,
        'recommendations': [],
    }
    ReportDelivery().deliver(sample)